// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Direct (unpooled) connection: Neon's PgBouncer pooler can interfere with
  // the DDL/advisory locks Migrate needs. The app itself connects separately
  // via the Neon driver adapter (src/lib/db.ts) using the pooled DATABASE_URL.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
